version: '3.8'

services:
  dis-app:
    image: ghcr.io/udanawetthasinghe/dis-app:latest
    container_name: dis-app
    restart: always
    ports:
      - "3000:3000"
      - "5000:5000"
    env_file:
      - .env

  forcast-app:
    image: ghcr.io/udanawetthasinghe/forcast-app:latest
    container_name: forcast-app
    restart: always
    ports:
      - "8080:8080"